### PR TITLE
Docker server

### LINKED ISSUE #11: Docker Container
Look at [this](https://stackoverflow.com/questions/28985714/run-apps-using-audio-in-a-docker-container) for getting audio in the docker container.

[docker documentation](https://docs.docker.com/guides/get-started/)

# Tasks
- [x] create a docker container
- [x] get audio input
- [x] build loopback devices from docker container (might be a script that runs then launches the docker container)
- [ ] output pipeline
- [ ] get peripheral devices from host machine

### PR DESCRIPTION
**Pull request by BCaven**
Tasks:
- [x] set up the flask server to run in the docker container
- [x] [dynamic](https://stackoverflow.com/questions/40963401/flask-dynamic-data-update-without-reload-page) page
- [x] flask server processes audio `POST` requests
- [x] audio from container host
- [x] audio client sends list of all sound devices to flask server
- [ ] GUI choose sound device to use/make loopback for
- [x]  WASAPI support
- [x]  loopback generation for selected audio output devices

### CODE REVIEW

**Comment by BCaven** [comment]
- [ ] WASAPI support
- [ ] loopback generation for selected audio output devices

**Review by AnarBayanzul — COMMENTED** [review]
still got a lot of work to go, buddy

**Comment by BCaven** [comment]
[soundcard](https://github.com/bastibe/SoundCard) handles loopback devices and the list of audio devices.
Still need to send that list to the flask server.

**Comment by BCaven** [comment]
Added Vue frontend for dynamic UI

**Review by ChadBrow — APPROVED** [review]
Looks good

**Pull request merged**
